CREATE TABLE emps_a_surveiller (
    NO DECIMAL(7),
    NOM VARCHAR(50),
    PRENOM VARCHAR(25),
    DT_ENTREE DATE,
    SALAIRE DECIMAL(11,2),
    PCT_COMMISSION DECIMAL(4,2)
);
GO

CREATE PROCEDURE ArchiveAndRemoveInactiveEmployees
AS
BEGIN
    -- Insert employees with no orders into archive table
    INSERT INTO emps_a_surveiller (NO, NOM, PRENOM, DT_ENTREE, SALAIRE, PCT_COMMISSION)
    SELECT NO, NOM, PRENOM, DT_ENTREE, SALAIRE, PCT_COMMISSION
    FROM E_EMPLOYE
    WHERE NO NOT IN (SELECT DISTINCT EMPLOYE_NO FROM E_COMMANDE);

    -- Delete employees with no orders
    DELETE FROM E_EMPLOYE
    WHERE NO NOT IN (SELECT DISTINCT EMPLOYE_NO FROM E_COMMANDE);
END;
